export interface ThemeConfig {
	bgColor: string;
	txtColor: string;
	optionBgActive: string;
	optionBg: string;
	optionBgHover: string;
	optionActiveTxtColor: string;
	optionTxtColor: string;
	optionBorder: string;
	optionActiveBorder: string;
	optionBorderHoverColor: string;
	radioColor: string;
	radioActiveColor: string;
	descColor: string;
	inputBg: string;
	inputBorder: string;
	inputBgFocus: string;
	inputBorderFocus: string;
	inputBgFilled: string;
	inputBorderFilled: string;
	starRateBorder: string;
	starRateBorderHover: string;
	starRateBorderActive: string;
	starRateActive: string;
	disabledColor: string;
	disabledBackground: string;
	disabledBorder: string;
	btnBg: string;
	btnTxt: string;
}

export type ThemeName = "light" | "yale" | "mirage" | "dark" | "purple";

export const themes: Record<ThemeName, ThemeConfig> = {
	yale: {
		bgColor: "#4D6AA6",
		txtColor: "#FFFFFF",
		optionBgActive: "#4D6AA6",
		optionBg: "#4D6AA6",
		optionBgHover: "#4D6AA6",
		optionActiveTxtColor: "#FFFFFF",
		optionTxtColor: "#FFFFFF",
		optionBorder: "#D1D5DB",
		optionActiveBorder: "#FF8A00",
		optionBorderHoverColor: "#A3BAFF",
		radioColor: "#D1D5DB",
		radioActiveColor: "#FF8A00",
		descColor: "#92A3BB",
		inputBg: "transparent",
		inputBorder: "#FF8A00",
		inputBgFocus: "#7B737B",
		inputBorderFocus: "#FF8A00",
		inputBgFilled: "transparent",
		inputBorderFilled: "#FF8A00",
		starRateBorder: "#D1D5DB",
		starRateBorderHover: "#FF8A00",
		starRateBorderActive: "#FF8A00",
		starRateActive: "#FF8A00",
		disabledColor: "#92A3BB",
		disabledBackground: "#3A4E7A",
		disabledBorder: "#5E7EC3",
		btnBg: "#FF8A00",
		btnTxt: "#FFFFFF",
	},
	dark: {
		bgColor: "#111111",
		txtColor: "#9CA3AF",
		optionBgActive: "transparent",
		optionBg: "transparent",
		optionBgHover: "#1E192C",
		optionActiveTxtColor: "#9CA3AF",
		optionTxtColor: "#9CA3AF",
		optionActiveBorder: "#8050F1",
		optionBorder: "#E4E8EF",
		optionBorderHoverColor: "#8050F1",
		radioColor: "#CBD5E1",
		radioActiveColor: "#8050F1",
		descColor: "#CBD5E1",
		inputBg: "transparent",
		inputBorder: "#CBD5E1",
		inputBgFocus: "#1E192C",
		inputBorderFocus: "#8050F1",
		inputBgFilled: "transparent",
		inputBorderFilled: "#8050F1",
		starRateBorder: "#92A3BB",
		starRateBorderHover: "#9871F4",
		starRateBorderActive: "#9871F4",
		starRateActive: "#8050F1",
		disabledColor: "#92A3BB",
		disabledBackground: "#1E192C",
		disabledBorder: "#3D3D3D",
		btnBg: "#8050F1",
		btnTxt: "#111111",
	},
	mirage: {
		bgColor: "#F6F7EB",
		txtColor: "#10182B",
		optionBgActive: "transparent",
		optionBg: "transparent",
		optionBgHover: "#EBEED4",
		optionActiveTxtColor: "#10182B",
		optionTxtColor: "#10182B",
		optionActiveBorder: "#809B00",
		optionBorder: "#E4E8EF",
		optionBorderHoverColor: "#809B00",
		radioColor: "#CBD5E1",
		radioActiveColor: "#809B00",
		descColor: "#92A3BB",
		inputBg: "transparent",
		inputBorder: "#CBD5E1",
		inputBgFocus: "#EBEED4",
		inputBorderFocus: "#8FAD00",
		inputBgFilled: "transparent",
		inputBorderFilled: "#809B00",
		starRateBorder: "#92A3BB",
		starRateBorderHover: "#8FAD00",
		starRateBorderActive: "#8FAD00",
		starRateActive: "#809B00",
		disabledColor: "#92A3BB",
		disabledBackground: "#E4E8EF",
		disabledBorder: "#CBD5E1",
		btnBg: "#809B00",
		btnTxt: "#FFFFFF",
	},
	light: {
		bgColor: "#F5F7FF",
		txtColor: "#10182B",
		optionBgActive: "transparent",
		optionBg: "transparent",
		optionBgHover: "#F5F7FF",
		optionActiveTxtColor: "#10182B",
		optionTxtColor: "#10182B",
		optionActiveBorder: "#A3BAFF",
		optionBorder: "#E4E8EF",
		optionBorderHoverColor: "#8CA9FF",
		radioColor: "#CBD5E1",
		radioActiveColor: "#8CA9FF",
		descColor: "#92A3BB",
		inputBg: "transparent",
		inputBorder: "#CBD5E1",
		inputBgFocus: "#F5F7FF",
		inputBorderFocus: "#A3BAFF",
		inputBgFilled: "transparent",
		inputBorderFilled: "#7094FF",
		starRateBorder: "#92A3BB",
		starRateBorderHover: "#A3BAFF",
		starRateBorderActive: "#A3BAFF",
		starRateActive: "#8CA9FF",
		disabledColor: "#92A3BB",
		disabledBackground: "#E4E8EF",
		disabledBorder: "#CBD5E1",
		btnBg: "#8CA9FF",
		btnTxt: "#FFFFFF",
	},
	purple: {
		bgColor: "#F5F7FF",
		txtColor: "#10182B",
		optionBgActive: "#F5F7FF",
		optionBg: "#FFFFFF",
		optionBgHover: "#A3BAFF",
		optionActiveTxtColor: "#10182B",
		optionTxtColor: "#10182B",
		optionActiveBorder: "#8CA9FF",
		optionBorder: "#E4E8EF",
		optionBorderHoverColor: "#7094FF",
		radioColor: "#CBD5E1",
		radioActiveColor: "#8CA9FF",
		descColor: "#637389",
		inputBg: "#f5f7ff",
		inputBorder: "#a3baff",
		inputBgFocus: "#f5f7ff",
		inputBorderFocus: "#8CA9FF",
		inputBgFilled: "#f5f7ff",
		inputBorderFilled: "#8CA9FF",
		starRateBorder: "#E4E8EF",
		starRateBorderHover: "#7094FF",
		starRateBorderActive: "#8CA9FF",
		starRateActive: "#8CA9FF",
		disabledColor: "#92A3BB",
		disabledBackground: "#E4E8EF",
		disabledBorder: "#CBD5E1",
		btnBg: "#10182B",
		btnTxt: "#FFFFFF",
	},
} as const;

/** Resolves theme colors with LIGHT fallbacks for any missing keys. */
export function getThemeColors(themeKey: ThemeName): ThemeConfig {
	return { ...themes.light, ...(themes[themeKey] || themes.light) };
}
